configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/bw.smk"
include: "rules/peaks.smk"

rule all:
	input:
		expand("results/bw/{sample}.bw", sample = samples) + ["results/qc/multiqc/multiqc_report.html"] + expand("results/peaks/{chip_sample}/{chip_sample}_peaks.filt.narrowPeak", chip_sample = chip_samples)
