configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/bw.smk"

rule all:
    input:
        expand("results/bw/{sample}.bw", sample = samples) + ["results/qc/multiqc/multiqc_report.html"]